version: '3'
services:
  mapperserver:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: mapperserver
    ports:
      - "5000:5000"
    
  mapperdb:
    build:
      context: .
      dockerfile: Dockerfile-db
      args:
        MYSQL_ROOT_PASSWORD: secret
    container_name: mapperdb
    ports:
      - "3306:3306"
