version: '3'
services:
  mapperdb:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: mapperdb
    ports:
      - "3306:3306"

  mapperserver:
    depends)on:
      - mapperdb
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: mapperserver
    ports:
      - "5000:5000"
