version: '3'
services:
  mapperserver:
    dockerfile: Dockerfile
    container_name: mapperserver
    ports:
      - "5000:5000"
    
  mapperdb:
    dockerfile: Dockerfile-db
    container_name: mapperdb
    ports:
      - "3306:3306"
